name: Branch Protection Checks

on:
  pull_request:
    paths-ignore:
      - '**/*.md'  # Ignore all Markdown files in any directory

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add specific test steps here if needed
      - name: Run Code Checks
        run: |
          echo "Running checks on essential files only."
